# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_userregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userregister',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password_r',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='username',
        ),
        migrations.AddField(
            model_name='userregister',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=20, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
