# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170720_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='user',
        ),
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregister',
            name='avatar',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
