# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
