# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_delete_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', 'Publish'), ('expectation', 'Expectation'), ('no publish', 'No Publish')], max_length=20, null=True),
        ),
    ]
